ALPINE_VERSION		= 3.5
DOCKERSPEC_VERSION	= 17.03.1-ce
ELASTIC_STACK_VERSION	= 5.3.0
OPENJDK_VERSION		= 8-jdk
SEARCHGUARD_ES_VERSION	= 11
SEARCHGUARD_KB_VERSION	= 1

DOCKERFILE_DEPS	 	+= ../Mk/docker.config.mk
