ALPINE_VERSION		= 3.6
CENTOS_VERSION		= 7.3.1611
DOCKERSPEC_VERSION	= ${ALPINE_VERSION}
ELASTIC_STACK_VERSION	= 5.3.0
OPENJDK_VERSION		= 8-jre
SEARCHGUARD_ES_VERSION	= 11
SEARCHGUARD_KB_VERSION	= 1

DOCKERFILE_DEPS	 	+= ../Mk/docker.config.mk
