version: 2

build_image: &build_image
  docker:
    - image: sicz/dockerspec:latest
  working_directory: ~/${CIRCLE_PROJECT_REPONAME}
  environment:
    - MAKEFLAGS=--no-print-directory
  steps:
    - run:
        name: Set up Environment
        command: |
          curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
          mv Mk-master ~/Mk
    - checkout
    - setup_remote_docker:
        version: 17.06.0-ce
    - run:
        name: Remote Docker engine version
        command: |
          docker version
    - run:
        name: Build image
        command: |
          make rebuild
    - run:
        name: Run container
        command: |
          make run
          make logs
    - run:
        name: Run tests
        command: |
          make rspec DOCKER_RSPEC_FORMAT=doc
