version: 2
jobs:
  build:
    docker:
      - image: sicz/dockerspec
    environment:
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Create Docker Sample Project
          command: |
            make create NAME=docker-sample-project
            echo "SUCCESS: The project has been created"
            echo
            echo "################################################################################"
            echo
            if ! make create NAME=docker-sample-project; then
              echo "SUCCESS: The project has not been overwritten"
            else
              echo "ERROR: The project has been overwritten by mistake"
              exit 1
            fi
            echo
            echo "################################################################################"
            echo
            make create NAME=docker-sample-project OVERWRITE=yes
            echo "SUCCESS: The project has been overwritten"
      - run:
          name: Build Docker Sample Project
          working_directory: docker-sample-project
          command: |
            ln -s . ../Mk
            make config-file
            make vars
            make docker-pull-baseimage docker-pull-dependencies docker-pull-testimage
            make ci
