version: 2
jobs:
  build:
    docker:
      - image: sicz/dockerspec:latest
    environment:
      - MAKEFLAGS=--no-print-directory
      - RSPEC_FORMAT=doc
    steps:
      - checkout
      - run:
          name: Checkout make files
          command: |
            cd ..
            curl -sSL https://github.com/SICZ/Mk/archive/master.tar.gz | tar -xzf -
            mv Mk-master Mk
      - setup_remote_docker:
          version: 17.06.0-ce
      - run:
          name: Pull Docker images
          command: |
            make docker-pull-baseimage
            make docker-pull-image || true
            make docker-pull-dependencies
            make docker-pull-testimage
      - run:
          name: sicz/sample-project:latest
          command: |
            make ci
      - deploy:
          name: Push images to the Docker Hub
          command: |
            # TODO:
            # if [ "${CIRCLE_BRANCH}" == "master" ]; then
            #   docker login -u ${DOCKER_HUB_USER} -p ${DOCKER_HUB_PASSWD}
            #   make docker-push-all
            # fi
