ARG BASE_IMAGE
FROM ${BASE_IMAGE}

# ARG MY_VERSION
# ARG MY_PATH="..."
#
# ENV \
#   DOCKER_USER="..." \
#   DOCKER_COMMAND="..." \
#   MY_PATH=${MY_PATH} \
#   MY_VERSION=${MY_VERSION} \
#   PATH=${MY_PATH}/bin:${PATH}
#
# RUN set -exo pipefail; \
#   ...
#
# COPY rootfs /
#
# RUN set -exo pipefail; \
#   ...
#
# CMD["--option"]
