###
### Default configuration
###

version: "3.3"

networks:
  default:

services:
  sample_project:
    image: ${DOCKER_IMAGE}
    # TODO: use real command or nothing
    # Listen on TCP port 7 (Echo Protocol) and mirror input to output
    command: /usr/bin/ncat -l 7 -k -c /bin/cat
    depends_on:
      - simple_ca
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - SERVER_CRT_HOST=${SERVER_CRT_HOST}
      - SERVER_KEY_PWD_FILE=/etc/ssl/private/server.pwd
      - SIMPLE_CA_URL=https://simple-ca.local
    networks:
      default:
        aliases:
          - sample-project.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_secrets:/run/secrets:ro

  simple_ca:
    image: ${SIMPLE_CA_IMAGE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      - SERVER_CRT_HOST=simple-ca.local
    networks:
      default:
        aliases:
          - simple-ca.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_data:/var/lib/simple-ca
      - simple_ca_secrets:/var/lib/simple-ca/secrets

  test:
    image: ${TEST_IMAGE}
    command: ${TEST_CMD}
    depends_on:
      - sample_project
    env_file:
      - ${TEST_ENV_FILE}
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      # TODO: Use a real URL
      - WAIT_FOR_TCP=sample-project.local:7
      # - WAIT_FOR_URL=https://sample-project.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_secrets:/run/secrets:ro
      # Use project dir as host volume for debugging tests if Docker host is local
      - ${TEST_PROJECT_DIR:-test_project_dir}:${PROJECT_DIR}
    working_dir: ${TEST_DIR}

  wait:
    image: ${TEST_IMAGE}
    depends_on:
      - sample_project
    environment:
      - DOCKER_ENTRYPOINT_DEBUG=true
      - DOCKER_ENTRYPOINT_INFO=true
      # TODO: Use a real URL
      - WAIT_FOR_TCP=sample-project.local:7
      # - WAIT_FOR_URL=http://sample-project.local https://sample-project.local
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - simple_ca_secrets:/run/secrets:ro

volumes:
  test_project_dir:
  simple_ca_data:
  simple_ca_secrets:
